name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"
      - run: pip install -r requirements.txt
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt"
      - uses: psf/black@22.3.0
        with:
          options: "--check --verbose"
          src: "./src"
          version: "22.3.0"
